# Generated by Django 6.0.3 on 2026-03-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_produto_categoria_produto_preco_custo_produto_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(max_length=50),
        ),
    ]
